config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:index, :new, :create, :destroy]
  resources :home, only: [:index]
  resources :portfolio, only: [:index]
  resources :stocks

  root 'stocks#index'

end

app/models/buy_order.rb
class BuyOrder < Order
  has_many :fills

  scope :book_ordered, -> { order(price: :asc, created_at: :asc) }

  def max_order_value
    price * quantity
  end
end

app/models/fill.rb
class Fill < ActiveRecord::Base
  belongs_to :buy_order
  belongs_to :sell_order

  validates :buy_order, :sell_order, presence: true
  validates :price, :quantity, numericality: { greater_than: 0 }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :stock
  belongs_to :user

  scope :unfulfilled, -> { where(fulfilled_at: nil) }
  scope :fulfilled, -> { where.not(fulfilled_at: nil) }
  scope :active, -> { where(status: nil).where(fulfilled_at: nil) }
  scope :by_recently_fulfilled, -> { order(fulfilled_at: :desc) }
  scope :by_recently_created, -> { order(created_at: :desc) }
  scope :stock, -> (stock) { where(stock: stock) }
  scope :for_user, -> (user) { where(user: user) }

  validates :stock, :user, presence: true
  validates :price, :quantity, numericality: { greater_than: 0 }
  validates :type, inclusion: { in: %w(BuyOrder SellOrder) }

  CANCELED = 'canceled'

  def cancel
    update(status: CANCELED) unless fulfilled?
  end

  def canceled?
    status == CANCELED
  end

  def active?
    !canceled? && !fulfilled?
  end

  def fulfilled?
    fulfilled_at.present?
  end

  def quantity_filled
    fills.sum(:quantity)
  end

  def quantity_unfilled
    quantity - quantity_filled
  end
end

app/models/sell_order.rb
class SellOrder < Order
  has_many :fills

  scope :book_ordered, -> { order(price: :desc, created_at: :asc) }
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :orders
  has_many :buy_orders
  has_many :sell_orders

  scope :for_user, -> (user) { includes(:orders).where(orders: {user: user}) }

  validates :name, :symbol, presence: true

  def market_price
    orders.fulfilled.by_recently_fulfilled.first.try(:price)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # define what happens on destroy
  has_many :orders
  has_many :buy_orders
  has_many :sell_orders

  after_initialize :default_values

  def default_values
    self.money ||= 10_000
  end

  def money_available
    buy_orders.unfulfilled.reduce(money) do |sum, order|
      sum - order.max_order_value
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    portfolio_index_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.for_user(current_user).by_recently_created
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = CreateOrder.new(order: current_user.orders.new(order_params)).call

    respond_to do |format|
      if @order.errors.empty?

        format.html { redirect_to orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.cancel

    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully canceled.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.for_user(current_user).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:stock_id, :type, :quantity, :price)
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @portfolio = GeneratePortfolio.new(user: current_user).call
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end

  private
    def stock_params
      params.require(:stock).permit(:name, :symbol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/index.html.erb
<h1>Home page</h1>

<%= link_to 'Stocks', stocks_path %>
<%= link_to 'My orders', orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevtrainStockexchange</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <nav>
        <%= link_to 'Stocks', stocks_path %>
        <%= link_to 'Portfolio', portfolio_index_path %>
        <%= link_to 'My orders', orders_path %>
      </nav>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.association :stock %>
  </div>
  <div class="field">
    <%= f.input :type, collection: ['BuyOrder', 'SellOrder'] %>
  </div>
  <div class="field">
    <%= f.input :quantity %>
  </div>
  <div class="field">
    <%= f.input :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Stock</th>
      <th>Order type</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Quantity Remaining</th>
      <th>Fulfilled at</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.stock.symbol, order.stock %></td>
        <td><%= order.type %></td>
        <td><%= order.quantity %></td>
        <td><%= order.price %></td>
        <td><%= order.quantity_unfilled %></td>
        <td><%= order.canceled? ? 'Canceled' : order.fulfilled_at %></td>
        <td><%= link_to 'Cancel', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } if order.active? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stock:</strong>
  <%= @order.stock_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @order.type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/portfolio/index.html.erb
<div>Hi <%= @user.email %></div>
<div>Current money: <%= @user.money %></div>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Quantity</th>
      <th>Purchase cost</th>
      <th>Current price</th>
      <th>Total value</th>
      <th>Change</th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio.each do |position| %>
      <tr>
        <td><%= position.stock.symbol %></td>
        <td><%= position.total_quantity %></td>
        <td><%= position.cost %></td>
        <td><%= position.market_price %></td>
        <td><%= position.total_value %></td>
        <td><%= position.percentage_change %>%</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.symbol %></td>
        <td><%= stock.name %></td>
        <td><%= stock.market_price %></td>
        <td><%= link_to 'Orders', stock %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @stock.name %> (<%= @stock.symbol %>)</h2>

<h3>Orders</h3>
<table>
  <thead>
    <tr>
      <th>Buy/Sell</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Quantity Remaining</th>
      <th>Fulfilled</th>
    </tr>
  </thead>

  <tbody>
    <% @stock.orders.by_recently_fulfilled.by_recently_created.each do |order| %>
      <tr>
        <td><%= order.type %></td>
        <td><%= order.price %></td>
        <td><%= order.quantity %></td>
        <td><%= order.quantity_unfilled %></td>
        <td><%= order.fulfilled_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', stocks_path %>